# Status codes
STATUS_OK = True
STATUS_FAIL = False

# Success codes
CODE_SUCCESS = 'SUCCESS'
# Error codes
CODE_FAIL = 'FAIL'
CODE_ALREADY_PAIRED = 'ALREADY_PAIRED'
CODE_INVALID_ARGUMENTS = 'INVALID_ARGUMENTS'
CODE_INVALID_KEY = 'INVALID_KEY'
CODE_TARGET_NOT_FOUND = 'TARGET_NOT_FOUND'
CODE_NOT_PAIRED = 'NOT_PAIRED'
CODE_COMMAND_ERROR = 'COMMAND_ERROR'

# Command errors
ERROR_INVALID_REQUEST = 'INVALID_REQUEST'
ERROR_INCOMPLETE_FORMAT = 'INCOMPLETE_FORMAT'
ERROR_INVALID_FORMAT = 'INVALID_FORMAT'
ERROR_UNKNOWN_COMMAND = 'UNKNOWN_COMMAND'